version: '3'
services:

  database: 
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: yourdb

  adminer: #web ui used to querry databse
    image: adminer
    restart: always
    depends_on: # ensures container starts after database is running
      - database
    ports:
      - 8080:8080 #go to http://localhost:8080/ in your webbrowser